export const routeNameMap = {
  Home: "首页",
  Explore: "探索",
  Hottest: "最热",
  HottestRecommend: "最热推荐",
  Recommend: "推荐",
  RecommendByUser: "基于用户的推荐",
  RecommendByItem: "基于项目的推荐",
  Favorite: "收藏",
  FavoriteMovie: "收藏的电影",
  Login: "登录",
  AdminConfig: "管理员配置",
  Setting: "设置",
  SystemSetting: "系统设置",
  Profile: "配置文件",
  EditProfile: "编辑用户文件",
  UserProfile: "用户资料",
}